pipeline {
    agent {
        docker {
            image 'composer:2.6' // includes PHP & Composer
            args '-u root:root'   // run as root to allow installing Node/npm
        }
    }

    environment {
        APP_NAME = "PRIMS"
        APP_ENV = "testing"
        DB_CONNECTION = "mysql"
        DB_HOST = "127.0.0.1"
        DB_PORT = "3306"
        DB_DATABASE = "prims_test"
        DB_USERNAME = "sail"       // change if different
        DB_PASSWORD = "password"   // change if different
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/jenkins/122_JM_CICD']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/APC-SoCIT/APC-2024-2025-T1-04-APC-Clinic---PRIMS.git',
                        credentialsId: 'prims'
                    ]]
                ])
            }
        }

        stage('Install PHP & Composer Dependencies') {
            steps {
                echo 'Installing Composer dependencies...'
                sh 'composer install --no-interaction --prefer-dist --optimize-autoloader'
            }
        }

        stage('Set APP Key & Run Migrations') {
            steps {
                echo 'Generating app key and migrating database...'
                sh '''
                php artisan key:generate
                php artisan migrate:fresh --seed
                '''
